In [1]:
import pandas as pd
import numpy as np
import pymysql
from datetime import datetime
import re
import boto3
import joblib
from io import BytesIO

aws_key = "AKIAR77AGTPERGGYPMYM"
aws_secret = "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"

# Crea un cliente de S3
s3 = boto3.client('s3', aws_access_key_id=aws_key, aws_secret_access_key=aws_secret)

# Especifica el nombre del bucket y la clave del archivo .pkl en S3

bucket_name = 'volana-datalake'
key_model = 'analytics/modelo_riesgo_volana/dev/06_model_output/documents/models/modelo_regresion_logistica.pkl'

key_model = 'analytics/modelo_riesgo_volana/dev/06_model_output/documents/models/modelo_regresion_logistica.pkl'
key_cc_scaler = 'analytics/modelo_riesgo_volana/dev/06_model_output/documents/scalers/data_cc_scaler.pkl'
key_demo_scaler = 'analytics/modelo_riesgo_volana/dev/06_model_output/documents/scalers/data_demo_scaler.pkl'

key_columnas_usar = 'analytics/modelo_riesgo_volana/dev/06_model_output/documents/lists/columnas_usar.txt'

key_deciles = 'analytics/modelo_riesgo_volana/dev/06_model_output/documents/lists/deciles.txt'

key_perdida_cosecha = 'analytics/modelo_riesgo_volana/dev/06_model_output/documents/lists/perdida_cosecha.txt'
# Descarga el archivo .pkl de S3

# Extrayendo prospectos

## Demográficos

In [2]:
ids_prospectos = np.array(pd.read_csv("./data/evaluation/prospectos_riesgo_11_28_23.csv").id_distribuidor.unique(), dtype = 'str')
ids = ", ".join(ids_prospectos)

In [3]:
sql_demograficos = f"""
 SELECT * FROM
    (select id, fecha_nacimiento,
           estado, sucursal, 
           escolaridad, estado_civil, dependientes, tipo_vivienda,
            sexo,
           tiempo_vivienda, ingreso_neto, experiencia,
           tipo_negocio, tiempo_op_negocio,capacidad_pago_semanal
           from demograficos_distribuidores 
    UNION
    select id, fecha_nacimiento,
           estado, sucursal, 
           escolaridad, estado_civil, dependientes, tipo_vivienda,
           sexo,
           tiempo_vivienda, ingreso_neto, experiencia,
           tipo_negocio, tiempo_op_negocio, capacidad_pago_semanal
           from cc_prospectos_demograficos
    ) as pen
     -- where pen.id in ({ids})
"""

In [4]:
cnx = pymysql.connect(host='159.89.90.197', port = 3306, user='antonio_diaz', passwd="4nT0ni_0.dZ",
                               charset='utf8',db = 'volana')
cursor = cnx.cursor()
cursor.execute(sql_demograficos)
data_demo = cursor.fetchall()
data_demo = pd.DataFrame(data_demo, columns=[i[0] for i in cursor.description])
cnx.close()
data_demo = data_demo.rename(columns = {"id":"id_distribuidor"})

### Limpieza

In [5]:
data_demo.drop(['capacidad_pago_semanal'], axis = 1, inplace=True)
variables_cambiar_por_moda = ['tipo_vivienda', 'estado_civil']
for var in variables_cambiar_por_moda:
    moda = data_demo[var].value_counts().index[0]
    data_demo[var] = data_demo[var].fillna(moda)
    print(f"moda para {var}: {moda}")

moda para tipo_vivienda: Familiar
moda para estado_civil: Casada (o)

In [6]:
data_demo.isna().any()

id_distribuidor      False
fecha_nacimiento      True
estado               False
sucursal             False
escolaridad          False
estado_civil         False
dependientes         False
tipo_vivienda        False
sexo                 False
tiempo_vivienda      False
ingreso_neto         False
experiencia          False
tipo_negocio          True
tiempo_op_negocio    False
dtype: bool

In [7]:
# Funciones necesarias
def processing_calcular_edad(fecha_nacimiento):
    fecha_nacimiento = pd.to_datetime(fecha_nacimiento) 
    fecha_actual = datetime.now()
    try:
        edad = fecha_actual.year - fecha_nacimiento.year - ((fecha_actual.month, fecha_actual.day) < (fecha_nacimiento.month, fecha_nacimiento.day))
        return edad
    except:
        return 35

def processing_quitar_cadenas_texto(txt):
    
    txt = txt.lower()
    txt = txt.replace(" ", "_")
    txt = txt.replace("_(o)", "")
    txt = txt.replace("$", "")
    txt = txt.replace(",", "")
    txt = txt.replace(".00", "")
    
    txt = txt.replace("á", "a")
    txt = txt.replace("é", "e")
    txt = txt.replace("í", "i")
    txt = txt.replace("ó", "o")
    txt = txt.replace("ú", "u")
    return txt

def processing_extraer_primer_numero(cadena):
    # Buscar el primer número en la cadena utilizando una expresión regular
    match = re.search(r'\d', cadena)
    
    # Si se encuentra un número, devolverlo como entero
    if match:
        return int(match.group())
    # Si no se encuentra ningún número, devolver 3
    else:
        return 3
    
def processing_agrupar_categorias(value_counts, lista):
    # Crear un diccionario para almacenar el mapeo de categorías
    mapeo = {}
    
    # Iterar sobre los value counts
    for categoria, conteo in value_counts.items():
        # Si el conteo es menor que 10, agruparlo en "otro"
        if conteo < 50:
            mapeo[categoria] = "otra"
        # Si el conteo es mayor o igual a 10, mantener la categoría original
        else:
            mapeo[categoria] = categoria
    
    # Aplicar el mapeo a la lista y devolver la lista resultante
    return [mapeo.get(categoria, "otra") for categoria in lista]


# Fecha nacimiento cambiarla por edad
data_demo['edad'] = data_demo.fecha_nacimiento.apply(processing_calcular_edad)
data_demo.drop(['fecha_nacimiento'], axis = 1, inplace=True)

# Estandarizar textos
for col_str in data_demo.select_dtypes(['object']).columns:
    
    data_demo[col_str] = data_demo[col_str].fillna("otra")
    data_demo[col_str] = data_demo[col_str].apply(processing_quitar_cadenas_texto)
    

data_demo.ingreso_neto = data_demo.ingreso_neto.astype(float)
#quitando el años y meses
data_demo.tiempo_op_negocio = data_demo.tiempo_op_negocio.apply(processing_extraer_primer_numero)

data_demo.tiempo_vivienda = data_demo.tiempo_vivienda.apply(processing_extraer_primer_numero)
data_demo.tiempo_vivienda = data_demo.tiempo_vivienda.astype(int)

data_demo.tipo_negocio = processing_agrupar_categorias(data_demo.tipo_negocio.value_counts(), data_demo.tipo_negocio)
data_demo.tipo_negocio = data_demo.tiempo_vivienda.astype(int)

data_demo.id_distribuidor = data_demo.id_distribuidor.astype(str)

In [8]:
data_demo

,id_distribuidor,estado,sucursal,escolaridad,estado_civil,dependientes,tipo_vivienda,sexo,tiempo_vivienda,ingreso_neto,experiencia,tipo_negocio,tiempo_op_negocio,edad
0,1,jalisco,ameca,secundaria,casada,3,propia,femenino,1,8765.0,no,1,1,47
1,19,jalisco,ameca,secundaria,casada,2,familiar,femenino,0,5980.0,no,0,1,34
2,29,jalisco,ameca,primaria,union_libre,2,familiar,femenino,0,5190.0,no,0,3,38
3,38,jalisco,ameca,secundaria,casada,2,rentada,femenino,4,10000.0,no,4,3,48
4,51,jalisco,ameca,primaria,casada,2,familiar,femenino,0,10000.0,no,0,1,48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14860,187939,mexico,chalco,primaria,union_libre,0,propia,femenino,0,12000.0,no,0,6,62
14861,187873,mexico,chalco,secundaria,union_libre,3,familiar,femenino,0,16000.0,no,0,8,41
14862,187868,distrito_federal,milpa_alta,secundaria,divorciada,0,familiar,femenino,0,8000.0,no,0,3,44
14863,187556,mexico,chalco,secundaria,soltera,1,familiar,femenino,0,14000.0,no,0,7,49
14864,187862,mexico,nezahualcoyotl,secundaria,casada,3,familiar,femenino,0,15.0,no,0,9,34

In [9]:
from sklearn.preprocessing import StandardScaler

import joblib
cols = ['dependientes', 'tiempo_vivienda', 'ingreso_neto', 'tipo_negocio',
       'tiempo_op_negocio', 'edad']

response = s3.get_object(Bucket=bucket_name, Key=key_demo_scaler)
demo_scaler_bytes = response['Body'].read()
# Carga el modelo usando joblib
scaler_loaded = joblib.load(BytesIO(demo_scaler_bytes))


variables_numericas_escaladas = pd.DataFrame(scaler_loaded.transform(data_demo[cols]), columns = cols)

data_demo_scaled = pd.concat([data_demo.drop(cols, axis=1), variables_numericas_escaladas], axis = 1)

KeyboardInterrupt:

## Creditos

In [10]:
sql_cc = f"""
SELECT 	consultas.id_distribuidor, 
		cuentas.*
FROM
 (SELECT 
	folioConsulta as 'folio', 
	sum(SaldoVencido) as 'saldo_vencido_total', 
    sum(NumeroPagosVencidos) as 'pagos_vencidos',
    count(folioConsulta) as 'creditos_totales',
    count(ClavePrevencion) as 'creditos_con_claves_prevencion',
    COUNT(IF(SaldoVencido = 0, NULL, 1)) as 'creditos_completados_con_atraso',
    COUNT(IF(SaldoVencido = 0, 1, NULL)) as 'creditos_completados_sin_atraso'
 FROM cc_prospectos_creditos 
 group by folioConsulta ) as cuentas 
 left join (select max(folioConsulta) as 'folio', idCliente as 'id_distribuidor' from cc_prospectos_folios group by idCliente) as consultas
 ON cuentas.folio = consultas.folio
 -- where consultas.id_distribuidor in ({ids})
 """

In [11]:
cnx = pymysql.connect(host='159.89.90.197', port = 3306, user='antonio_diaz', passwd="4nT0ni_0.dZ",
                               charset='utf8',db = 'volana')
cursor = cnx.cursor()
cursor.execute(sql_cc)
data_cc = cursor.fetchall()
data_cc = pd.DataFrame(data_cc, columns=[i[0] for i in cursor.description])
cnx.close()

### Limpieza

In [12]:
data_cc.id_distribuidor = data_cc.id_distribuidor.astype(str)
data_cc.folio = data_cc.folio.astype(str)

data_cc.creditos_con_claves_prevencion = data_cc.creditos_con_claves_prevencion / data_cc.creditos_totales
data_cc.creditos_completados_con_atraso = data_cc.creditos_completados_con_atraso / data_cc.creditos_totales

data_cc.drop(['creditos_completados_sin_atraso'], axis = 1, inplace=True)

cols = ['saldo_vencido_total', 'pagos_vencidos', 'creditos_totales']

response = s3.get_object(Bucket=bucket_name, Key=key_cc_scaler)
demo_scaler_bytes = response['Body'].read()
# Carga el modelo usando joblib
scaler_loaded = joblib.load(BytesIO(demo_scaler_bytes))
#scaler_loaded = joblib.load('./data/staging/data_cc_scaler.pkl')

variables_numericas_escaladas = pd.DataFrame(scaler_loaded.transform(data_cc[cols]), columns = cols)

In [13]:
data_cc_scaled = pd.concat([data_cc.drop(cols, axis = 1), variables_numericas_escaladas], axis = 1)

## Merge

In [14]:
data_final = pd.merge(data_demo_scaled, data_cc_scaled, on = 'id_distribuidor')

In [15]:
data_final = data_final.drop(['folio'], axis = 1)
data_final.head()

,id_distribuidor,estado,sucursal,escolaridad,estado_civil,tipo_vivienda,sexo,experiencia,dependientes,tiempo_vivienda,ingreso_neto,tipo_negocio,tiempo_op_negocio,edad,creditos_con_claves_prevencion,creditos_completados_con_atraso,saldo_vencido_total,pagos_vencidos,creditos_totales
0,116,mexico,chimalhuacan_2,bachillerato,divorciada,propia,femenino,no,-0.781247,0.663563,-0.074213,0.663563,-1.015644,0.929008,0.186916,0.009346,-0.544050,-0.819401,1.314633
1,2174,mexico,chimalhuacan_2,secundaria,casada,familiar,femenino,no,1.070597,-0.339031,-0.074037,-0.339031,1.679599,0.377642,0.631579,0.157895,0.254597,-0.248740,-0.520960
2,2564,mexico,nezahualcoyotl_2,bachillerato,casada,propia,femenino,no,-0.781247,-0.339031,0.096792,-0.339031,0.331977,1.401608,0.593750,0.218750,0.035503,0.086943,-0.249793
3,3481,mexico,chimalhuacan_2,secundaria,casada,propia,femenino,si,-0.781247,-0.339031,0.058791,-0.339031,-1.015644,1.874208,0.093023,0.000000,-0.616726,-1.020810,-0.020344
4,5812,distrito_federal,nezahualcoyotl_2,bachillerato,soltera,familiar,femenino,no,-0.781247,-0.840328,0.020790,-0.840328,1.230391,-0.331258,0.583333,0.416667,0.086418,0.131701,-0.666973

In [16]:
data_final_guardar = pd.concat([pd.get_dummies(data_final.drop("id_distribuidor", axis = 1)), data_final["id_distribuidor"]], axis = 1)

In [17]:
data_final_modelo = data_final_guardar.drop(["id_distribuidor"], axis = 1)

### Ordenando las columnas

In [18]:
response = s3.get_object(Bucket=bucket_name, Key=key_columnas_usar)
columnas_bytes = response['Body'].read()
# Carga el modelo usando joblib
columnas = np.loadtxt(BytesIO(columnas_bytes), dtype=str)

#columnas = np.loadtxt('./data/master/columnas_usar.txt', dtype=str)

In [19]:
data_final_modelo.drop(np.setdiff1d(data_final_modelo.columns,columnas), axis = 1, inplace=True)

In [20]:
for col in np.setdiff1d(columnas, data_final_modelo.columns):
    data_final_modelo[col] = 0

In [21]:
data_final_modelo = data_final_modelo[columnas]

### Corriendo el modelo

In [22]:
response = s3.get_object(Bucket=bucket_name, Key=key_model)
model_bytes = response['Body'].read()

# Carga el modelo usando joblib
loaded_model = joblib.load(BytesIO(model_bytes))

In [23]:
data_final_modelo.head(1)

,dependientes,tiempo_vivienda,ingreso_neto,tipo_negocio,tiempo_op_negocio,edad,creditos_con_claves_prevencion,creditos_completados_con_atraso,saldo_vencido_total,pagos_vencidos,...,estado_civil_union_libre,estado_civil_viuda,tipo_vivienda_familiar,tipo_vivienda_otro,tipo_vivienda_propia,tipo_vivienda_rentada,sexo_femenino,sexo_masculino,experiencia_no,experiencia_si
0,-0.781247,0.663563,-0.074213,0.663563,-1.015644,0.929008,0.186916,0.009346,-0.54405,-0.819401,...,0,0,0,0,1,0,1,0,1,0

In [24]:
data_final_modelo.columns = np.array(data_final_modelo.columns, dtype = 'str')

In [25]:
data_final['riesgo'] = loaded_model.predict_proba(data_final_modelo).T[0]

### Añadiendo la pérdida de cosecha y el grupo de riesgo

In [26]:
response = s3.get_object(Bucket=bucket_name, Key=key_deciles)
cortes_probabilidad_bytes = response['Body'].read()
# Carga el modelo usando joblib
cortes_probabilidad = np.loadtxt(BytesIO(cortes_probabilidad_bytes), dtype=float)*100

response = s3.get_object(Bucket=bucket_name, Key=key_perdida_cosecha)
cosechas_estimadas_bytes = response['Body'].read()
# Carga el modelo usando joblib
cosechas_estimadas = np.loadtxt(BytesIO(cosechas_estimadas_bytes), dtype=float)*100

In [27]:
#cortes_probabilidad = np.loadtxt('./data/master/deciles.txt', dtype=float)*100
#cosechas_estimadas = np.loadtxt('./data/master/perdida_cosecha.txt', dtype=float)

In [28]:
cosechas_estimadas

array([ 0.59818465,  1.82981294,  3.32205965,  3.11605024,  3.37410505,
        3.97705569,  5.24391098,  5.82837159,  7.90005191, 11.22693992])

In [29]:
def setcut_prob(p, grupo_ = True):
    p = p*100

    for cut in cortes_probabilidad:
        if cut > p:
            break
            
    grupo = np.where(cortes_probabilidad == cut)[0][0] 
    if grupo_:
        return grupo
    else:
        return cosechas_estimadas[grupo - 1]

In [30]:
data_final['grupo_riesgo'] = data_final['riesgo'].apply(lambda x: f"Canasta {setcut_prob(x, grupo_ = True)}")
data_final['perdida_cosecha_canasta'] = data_final['riesgo'].apply(lambda x: setcut_prob(x, grupo_ = False))

### Regresando la capacidad de pago

In [31]:
data_final['cuota_semanal_que_puede_cubrir'] = 1_000

In [32]:
data_final_modelo_tasas = data_final[['id_distribuidor', 'perdida_cosecha_canasta', 'cuota_semanal_que_puede_cubrir', 'riesgo', 'grupo_riesgo']]

In [33]:
rentabilidad_obj = 0.4

def getVals_all(X, t_max, d, c, pc, print_ = False):
    tasas = []
    rentabilidades = []
    factible = []
    por_pagar_sem = []

    for t in range(75, int(t_max*100)+1, 1):

        total_pagado, pago_real_semanal, rentabilidad, tasa_ajustada = getVals( X = X, 
                                                                                d = d, 
                                                                                t = t/100, 
                                                                                pc = pc)
        tasas.append(t)
        rentabilidades.append(rentabilidad)

        factible.append( ((total_pagado / d) < c) * (rentabilidad >= rentabilidad_obj))

        por_pagar_sem.append(total_pagado / d)

        if print_:
            print(f"Tasa: {t} - \tpagado {total_pagado:.2f} - pagado por semana {total_pagado/d:.2f} - capacidad {c} - rentabilidad {rentabilidad:.3f}")

    tasas = np.array(tasas)
    rentabilidades = np.array(rentabilidades)
    por_pagar_sem = np.array(por_pagar_sem)

    return tasas, rentabilidades, por_pagar_sem


def getVals(X, d, t, pc):
    fijos = 20.6 * d
    originacion = 20.6
    fondeo = (0.20/52) * X * d
    perdida_cosecha = abs(pc) * X 

    costos = fijos + originacion + fondeo + perdida_cosecha

    # ==============

    pagado = lambda X, t, d: ( (X*t*(1+t)**d) / (- 1 + (1+t)**d) ) * d

    t_semanal_con_iva = (t/52)*1.16
    total_pagado = pagado(X, t_semanal_con_iva, d)

    ingresos_intereses = total_pagado - X

    seguros = {4_000 : 26, 21_000 : 29, 51_000 : 30, np.inf: 31}

    ingreso_seguro = 0.0

    key_ant = 0
    for s in seguros.keys():
        if X < s and X > key_ant:
            ingreso_seguro = seguros[s]

        key_ant = s

    marginal = ingresos_intereses - costos

    rentabilidad = marginal / ingresos_intereses

    cuanto_deberia_ganar_de_intereses = costos/(1 - rentabilidad_obj)

    cuanto_me_deberian_depagar = cuanto_deberia_ganar_de_intereses + X

    pago_real_semanal = cuanto_me_deberian_depagar / d

    # Averiguar cómo ajustar la tasa
    tasa_ajustada = t


    return total_pagado, pago_real_semanal, rentabilidad, tasa_ajustada


def find_tasa_fija(tasa_opt):
    tasas_fijas = [75, 80, 85, 90, 95, 100, 105, 110, 112, 115, 117, 120, 122, 127, 132, 137, 142, 147]
    for tf in tasas_fijas:
        if tf >= tasa_opt:
            return tf

def ajustarTasa(X, t_max, d, c, pc):
    """
    In:
        X[float]: Monto solicitado del préstamo original
        t_max[float]: tasa anual máxima (regularmente 1.47)
        d[int]: número de semanas de duración del préstamo (regularmente 16)
        c[float]: capacidad de pago semanal (de las tablas ingestado)
        pc[float]: pérdida de cosecha estimada 
    Out:
        estatus[bool]: estatus del crédito - rechazo si False / aceptación si True
        tasa_minima[float] = tasa mínima rentable
        tasa_sugerida[float] = tasa óptima
        resultado_txt[str] = texto que describe el resultado
    """
    """
    10,000 --> False rechazado
    9,000 --> False
    8,000, ..., 5,000 -> Aprobado

    ID
    1 - 10,000  - RECHAZO
    1 - 9 ,000  - RECHAZO <-

    1 - 8 ,000  - ACEPTADO
    1 - 7 ,000  - ACEPTADO
    1 - 6 ,000  - ACEPTADO

    9,000, ..., 5,000
    """


    estatus       = False 
    tasa_minima   = 0.0
    tasa_sugerida = 0.0
    resultado_txt = ""


    tasas, rentabilidades, por_pagar_sem = getVals_all(X = X, 
                                                   t_max = t_max,
                                                   d = d,
                                                   c = c,
                                                   pc = pc,
                                                   print_ = False)

    factible_rentabilidad = (rentabilidades > rentabilidad_obj)
    factible_pago = (np.array(por_pagar_sem) < c)
    factible = factible_rentabilidad * factible_pago
    rentabilidades *= 100


    if factible.sum() != 0:

            tasa_minima = find_tasa_fija(min(tasas[factible]))
            tasa_sugerida = find_tasa_fija(max(tasas[factible]))

            resultado_txt = f"Tasa anual sugerida es de {tasa_sugerida}% con rentabilidad: {max(rentabilidades[factible]):.2f}% y pagando {max(por_pagar_sem[factible]):.2f}"
            resultado_txt += "\n"
            resultado_txt += f"Tasa anual mínima posible es de {tasa_minima}% con rentabilidad: {min(rentabilidades[factible]):.2f}% y pagando {min(por_pagar_sem[factible]):.2f}"
            estatus = True


    elif factible.sum() == 0:

        resultado_txt += f"No existe un intervalo factible, se rechaza el crédito\n"

        posibles_tasas = np.where((rentabilidades > 40))[0]
        if len(posibles_tasas) > 0:
            resultado_txt += f"El pago mínimo necesario para tener una rentabilidad del 40% es de: {por_pagar_sem[posibles_tasas[0]]:.2f}"
        else:
            resultado_txt += f"Su capacidad de pago no asegura tener una rentabilidad del 40%\n"

            resultado_txt += f"El pago semanal mínimo es de {min(por_pagar_sem):.2f} (con rentabilidad de {min(rentabilidades):.2f}%) y se tiene capacidad hasta {c}\n"

            resultado_txt += f"La rentabilidad máx alcanzada es de {max(rentabilidades):.2f}% (con pago de {max(por_pagar_sem):.2f}) y se tiene como objetivo {rentabilidad_obj*100}%"

    elif factible.sum() == len(factible):
        resultado_txt = f"Todas las tasas son viables, se asigna la mayor de {find_tasa_fija(max(tasas))}% anual"
        estatus = True
        tasa_minima = find_tasa_fija(min(tasas[factible]))
        tasa_sugerida = find_tasa_fija(max(tasas[factible]))

    return estatus, resultado_txt, tasa_minima, tasa_sugerida


########################################################################## Calculo de Riesgo
####### Asignacion de Riesgo #######
pdf_modelo = data_final_modelo_tasas[['id_distribuidor', 'perdida_cosecha_canasta', 'cuota_semanal_que_puede_cubrir', 'riesgo', 'grupo_riesgo']] 

d = 16
t_max = 1.47
resultado = []

for row in pdf_modelo.iterrows():
    pc = row[1]['perdida_cosecha_canasta']/100
    c  = row[1]['cuota_semanal_que_puede_cubrir']
    id_ = int(row[1]['id_distribuidor'])
    prob = float(row[1]['riesgo'])
    grp = row[1]['grupo_riesgo']
    alguno_paso = 0
    for X in range(10_000, 4_000, -1_000):
        estatus, resultado_txt, tasa_minima, tasa_sugerida = ajustarTasa(X, t_max, d, c, pc)
        if estatus:
            resultado.append([id_, resultado_txt, X, tasa_minima, tasa_sugerida, prob, grp])
            alguno_paso = 1
    if alguno_paso == 0:
        _, resultado_txt, _, _ = ajustarTasa(X, t_max, d, c, pc)
        resultado.append([id_, resultado_txt, 0, 0, 0, prob, grp])

pdf_riesgo = pd.DataFrame(resultado)

pdf_riesgo.columns = ["id_distribuidor","resultado_txt","monto_autorizado", "tasa_minima","tasa_sugerida", "probabilidad", "grupo_riesgo"]

# Obtener fecha y hora actual     
dia = "ahorita"
hora = "hoy"

pdf_riesgo["fecha"] = dia
pdf_riesgo["hora"] = hora

#pdf_riesgo.to_csv("./data/evaluation/prospectos_evaluados_modelo_volana.csv", index=True)

key_final = 'analytics/modelo_riesgo_volana/dev/06_model_output/prospectos_modelo_volana/pdf_riesgo.csv'

# Convertir DataFrame a CSV en memoria
csv_buffer = pdf_riesgo.to_csv(index=False)

# Subir el archivo CSV a S3 directamente desde la memoria
response = s3.put_object(Bucket=bucket_name, Key=key_final, Body=csv_buffer)

In [35]:
pdf_riesgo['fecha'] = '2024-05-07'
pdf_riesgo['hora'] = '00:00:00'

In [37]:
pdf_riesgo.to_csv("./data/evaluation/prospectos_evaluados_modelo_volana.csv", index=True)

## Agrupando

In [15]:
pdf_riesgo = pd.read_csv("./data/evaluation/prospectos_evaluados_modelo_volana.csv")

In [19]:
pdf_riesgo.head()

,Unnamed: 0,id_distribuidor,resultado_txt,monto_autorizado,tasa_minima,tasa_sugerida,probabilidad,grupo_riesgo,fecha,hora
0,0,116,Tasa anual sugerida es de 147% con rentabilida...,10000,110,147,0.33408,Canasta 3,2024-05-07,00:00:00
1,1,116,Tasa anual sugerida es de 147% con rentabilida...,9000,112,147,0.33408,Canasta 3,2024-05-07,00:00:00
2,2,116,Tasa anual sugerida es de 147% con rentabilida...,8000,115,147,0.33408,Canasta 3,2024-05-07,00:00:00
3,3,116,Tasa anual sugerida es de 147% con rentabilida...,7000,120,147,0.33408,Canasta 3,2024-05-07,00:00:00
4,4,116,Tasa anual sugerida es de 147% con rentabilida...,6000,127,147,0.33408,Canasta 3,2024-05-07,00:00:00

In [22]:
pdf_riesgo.groupby('id_distribuidor').agg({"monto_autorizado": max, "tasa_minima":min, "grupo_riesgo": max})\

In [25]:
temp = pdf_riesgo.groupby('id_distribuidor').agg({"monto_autorizado": max, "tasa_minima":min, "grupo_riesgo": max})

temp['riesgo'] = temp.grupo_riesgo.apply(lambda x: int(x.replace("Canasta ","")))

In [26]:
temp.to_csv("./data/evaluation/prospectos_evaluados_modelo_volana_agrupado_2024_05_11.csv")